### ISSUE TITLE
RIFF Header Size When Adding

### ISSUE THREAD

**Issue by wdnaeng** [synesthesiam/wav-chunk#1]
Hey friend, love the code, super readable, very educational. 

When adding chunks, the RIFF size doesn't change, so the change is not always detectable when the file is read. 

I changed the following lines in INIT to update the RIFF size when adding a chunk.

def read_after_format(
    file: typing.IO[bytes], out_file: typing.Optional[typing.IO[bytes]] = None, extra_size: int = 0

...

    if out_file:
        write_name(out_file, riff)
        new_riff_size = riff_size + extra_size
        write_size(out_file, new_riff_size)

...

def read_after_data(
    file: typing.IO[bytes], out_file: typing.Optional[typing.IO[bytes]] = None, extra_size: int = 0
):
    read_after_format(file, out_file=out_file, extra_size=extra_size)

...

    read_after_data(wav_file, out_file=out_file, extra_size=len(chunk_data))

...

BSI InfoEdit is reading my metadata adds now!

I reckon the same hook could be done when doing a get_chunk with remove and an out_file. 

I have no idea what I'm doing, so sorry if this is the wrong place or wrong way.

**Comment by wdnaeng** [comment]
Oo! I gotta add an additional +8 for the name and size parts of the new chunk not included in len(chunk_data)

**Comment by synesthesiam** [comment]
Thanks for taking a look at this! Can you submit a PR when you're done so I can take a look please?

**Comment by wdnaeng** [comment]
Thanks, hope I did that right, first time using anything like GitHub.
